In [59]:
import numpy as np 
import pandas as pd

In [60]:
df = pd.read_csv("email.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [61]:
df.groupby("Category").describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [62]:
df.replace({ "ham":0, "spam":1 },inplace=True)
df.head()

Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [63]:
X = df["Message"]
y = df["Category"]

In [64]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state = 10)

In [77]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer()

x_train_data = cv.fit_transform(x_train.values)

x_train_data.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [78]:
from sklearn.naive_bayes import MultinomialNB

In [79]:
model = MultinomialNB()
model.fit(x_train_data,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [80]:
x_test_data = cv.fit_transform(x_test)

scipy.sparse.csr.csr_matrix

In [94]:
email = ["hi ruhan, lets play football to evening. I hope you will come at 4 pm .thanks","hurra!!! upto 800% free offer"]

In [95]:
email_data = cv.transform(email)
email_data.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [101]:
model.predict(email_data)

ValueError: dimension mismatch

In [97]:
from sklearn.pipeline import Pipeline

plc = Pipeline([("vectorizer", CountVectorizer()),("nb", MultinomialNB())])

In [98]:
plc.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [99]:
plc.score(x_test,y_test)

0.9829596412556054

In [102]:
plc.predict(email)

array([0, 1], dtype=int64)